type AddCurrencyToken @entity(immutable: true) {
  id: Bytes!
  currencyToken: Bytes! # address
  priceFeedAddress: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type Approval @entity(immutable: true) {
  id: Bytes!
  owner: Bytes! # address
  approved: Bytes! # address
  tokenId: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type ApprovalForAll @entity(immutable: true) {
  id: Bytes!
  owner: Bytes! # address
  operator: Bytes! # address
  approved: Boolean! # bool
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type ConsecutiveTransfer @entity(immutable: true) {
  id: Bytes!
  fromTokenId: BigInt! # uint256
  toTokenId: BigInt! # uint256
  from: Bytes! # address
  to: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type NewSubPrize @entity {
  id: Bytes!
  seriesID: BigInt! # uint256
  subPrizeID: BigInt! # uint256
  prizeGroup: String! # string
  subPrizeName: String! # string
  subPrizeRemainingQuantity: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
  belongSeries: NewSeries!
}

type LastPrizeDraw @entity {
  id: Bytes!
  requestId: BigInt! # uint256
  seriesID: BigInt! # uint256
  randomWord: [BigInt!] # uint256
  quantity: BigInt # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type LastPrizeWinner @entity(immutable: true) {
  id: Bytes!
  requestId: BigInt! # uint256
  randomWord: [BigInt!] # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type NewSeries @entity {
  id: Bytes!
  seriesID: BigInt! # uint256
  seriesName: String! # string
  totalTicketNumbers: BigInt! # uint256
  remainingTicketNumbers: BigInt! # uint256
  priceInUSDTWei: BigInt! # uint256
  priceInTWD: BigInt! # uint256
  isGoodsArrived: Boolean! # bool
  estimateDeliverTime: BigInt! # uint256
  exchangeExpireTime: BigInt! # uint256
  exchangeTokenURI: String! # string
  unrevealTokenURI: String! # string
  revealTokenURI: String! # string
  seriesMetaDataURI: String! # string
  lastPrizeOwner: [Bytes!] # address
  isRefund: Boolean! # bool
  isPreOrder: Boolean! # bool
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
  recentIPFSHash: Bytes!
  currentIchibanSeries: IchibanSeries
  NewPrizes: [NewSubPrize!] @derivedFrom(field: "belongSeries")
  NewTicketStatuses: [NewTicketStatus!] @derivedFrom(field: "belongSeries")
}

type IchibanSeries @entity(immutable: true) {
  id: Bytes!
  hash: String!
  belongSeries: NewSeries!
  onChainSeriesID: BigInt
  twContent: String
  enContent: String
  twTitle: String
  enTitle: String
  thumbnailSrc: String
  backgroundSrc: String
  twSubContent: String
  enSubContent: String
  IchibanKujiPrizes: [IchibanKujiPrize!] @derivedFrom(field: "belongSeries")
  NewTicketStatuses: [NewTicketStatus!]
    @derivedFrom(field: "belongIchibanSeries")
}

type IchibanKujiPrize @entity(immutable: true) {
  id: Bytes!
  hash: String!
  belongSeries: IchibanSeries!
  prizeId: String
  type: String
  twGroupName: String
  enGroupName: String
  size: String
  prizeImageSrc: String
  groupTotalQuantity: String
  twGroupDescription: String
  enGroupDescription: String
  isBlindBox: Boolean
  IchibanKujiSubPrizes: [IchibanKujiSubPrize!]
    @derivedFrom(field: "belongIchibanPrize")
}

type IchibanKujiSubPrize @entity(immutable: true) {
  id: Bytes!
  hash: String!
  belongIchibanPrize: IchibanKujiPrize!
  subPrizeId: String
  prizeGroup: String
  twName: String
  enName: String
  size: String
  subPrizeImageSrc: String
  quantity: String
  twDescription: String
  enDescription: String
}

type NewTicketStatus @entity {
  id: Bytes!
  tokenID: BigInt! # uint256
  seriesID: BigInt! # uint256
  tokenRevealedPrize: BigInt! # uint256
  tokenExchange: Boolean! # bool
  tokenRevealed: Boolean! # bool
  tokenOwner: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
  belongSeries: NewSeries!
  belongIchibanSeries: IchibanSeries!
  belongIchibanSubPrize: IchibanKujiSubPrize
}

type RefundSeries @entity(immutable: true) {
  id: Bytes!
  seriesID: BigInt! # uint256
  isRefund: Boolean! # bool
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type RevealDrawFulfilled @entity(immutable: true) {
  id: Bytes!
  requestId: BigInt! # uint256
  seriesID: BigInt! # uint256
  randomWords: [BigInt!]! # uint256[]
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type RevealDrawSent @entity {
  id: Bytes!
  requestId: BigInt! # uint256
  seriesID: BigInt # uint256
  tokenIDs: [BigInt!]! # uint256[]
  randomWords: [BigInt!]! # uint256[]
  subPrizesRemainingQuantities: [BigInt!] # uint256[]
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type Transfer @entity(immutable: true) {
  id: Bytes!
  from: Bytes! # address
  to: Bytes! # address
  tokenId: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type UpdatePrize @entity(immutable: true) {
  id: Bytes!
  seriesID: BigInt! # uint256
  subPrizeID: BigInt! # uint256
  subPrizeRemainingQuantity: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type UpdateSeriesInformation @entity(immutable: true) {
  id: Bytes!
  seriesID: BigInt! # uint256
  isGoodsArrived: Boolean! # bool
  estimateDeliverTime: BigInt! # uint256
  exchangeExpireTime: BigInt! # uint256
  exchangeTokenURI: String! # string
  unrevealTokenURI: String! # string
  revealTokenURI: String! # string
  seriesMetaDataURI: String! # string
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type UpdateSeriesLastPrizeOwner @entity(immutable: true) {
  id: Bytes!
  seriesID: BigInt! # uint256
  lastPrizeOwner: [Bytes!] # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type UpdateSeriesRemainingTicketNumbers @entity(immutable: true) {
  id: Bytes!
  seriesID: BigInt! # uint256
  remainingTicketNumbers: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type UpdateTicketStatus @entity(immutable: true) {
  id: Bytes!
  tokenID: BigInt! # uint256
  seriesID: BigInt! # uint256
  tokenRevealedPrize: BigInt! # uint256
  tokenExchange: Boolean! # bool
  tokenRevealed: Boolean! # bool
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}
